- name:
  hosts: all
  become: yes
  pre_tasks:
    - name: update cache and cleanup package
      apt:
        update_cache: yes
        autoremove: yes
  roles:
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - common
    - mackerel-agent
    - lexicon
    - dehydrated
    - nginx
