- name:
  hosts: all
  become: yes
  pre_tasks:
    - name: update cache and cleanup package
      apt:
        update_cache: yes
        autoremove: yes
  roles:
    - role: dev-sec.os-hardening
      tags:
        - role_dev-sec
        - role_dev-sec-os
    - role: dev-sec.ssh-hardening
      tags:
        - role_dev-sec
        - role_dev-sec-ssh
    - role: common
      tags: role_common
    - role: mackerel-agent
      tags: role_mackerel-agent
    - role: lexicon
      tags: role_lexicon
    - role: dehydrated
      tags: role_dehydrated
    - role: mariadb
      tags: role_mariadb
    - role: nginx
      tags: role_nginx
    - role: php
      tags: role_php
  tasks:
    - name: clound-init hostname setting
      block:
        - name: check clound-init config
          stat:
            path: /etc/cloud/cloud.cfg
          register: result
        - name: remove clound-init hostname reset setting
          lineinfile:
            path: /etc/cloud/cloud.cfg
            regexp: "^manage_etc_hosts: (yes|on|true)"
            state: absent
          when: result.stat.exists
      tags:
        - hostname
